language: cpp
compiler:
 - gcc
 - clang
os:
- linux
cache:
 apt: true
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7
install:
# Install CMake 3.4.3
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget --no-check-certificate http://cmake.org/files/v3.4/cmake-3.4.3-Linux-x86_64.tar.gz       ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar -xzf cmake-3.4.3-Linux-x86_64.tar.gz                                                      ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then wget --no-check-certificate http://cmake.org/files/v3.4/cmake-3.4.3-Darwin-x86_64.tar.gz      ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then tar -xzf cmake-3.4.3-Darwin-x86_64.tar.gz                                                     ;fi
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd tests && ../cmake-3.4.3-Linux-x86_64/bin/cmake . && (make -j 8 || make VERBOSE=1)                      ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then cd tests && ../cmake-3.4.3-Darwin-x86_64/CMake.app/Contents/bin/cmake . && (make -j 8 || make VERBOSE=1)  ;fi

#- cd tests && cmake . && (make -j 8 || make VERBOSE=1)
